// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMhw3jZQRHI6nIffINTP7y098PKNeLzwY',
    appId: '1:121729798162:web:1eb0d62b5e58e82ab288cb',
    messagingSenderId: '121729798162',
    projectId: 'ecommerce-39620',
    authDomain: 'ecommerce-39620.firebaseapp.com',
    storageBucket: 'ecommerce-39620.appspot.com',
    measurementId: 'G-F63Z059SWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcf5zcIYlTZKwCuBbfhdwv95sXwNPPRQs',
    appId: '1:121729798162:android:b085cfef915d32c9b288cb',
    messagingSenderId: '121729798162',
    projectId: 'ecommerce-39620',
    storageBucket: 'ecommerce-39620.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoFGIu6L11gex9FAzXg__5zNTU_vju_nA',
    appId: '1:121729798162:ios:91ce4024e34edc3bb288cb',
    messagingSenderId: '121729798162',
    projectId: 'ecommerce-39620',
    storageBucket: 'ecommerce-39620.appspot.com',
    androidClientId: '121729798162-frfmc4bjarlene5iu8vaa5383j3hn0tu.apps.googleusercontent.com',
    iosClientId: '121729798162-6ubbj46n84itfim2kusmgnqq8c49l69h.apps.googleusercontent.com',
    iosBundleId: 'com.example.fullECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoFGIu6L11gex9FAzXg__5zNTU_vju_nA',
    appId: '1:121729798162:ios:91ce4024e34edc3bb288cb',
    messagingSenderId: '121729798162',
    projectId: 'ecommerce-39620',
    storageBucket: 'ecommerce-39620.appspot.com',
    androidClientId: '121729798162-frfmc4bjarlene5iu8vaa5383j3hn0tu.apps.googleusercontent.com',
    iosClientId: '121729798162-6ubbj46n84itfim2kusmgnqq8c49l69h.apps.googleusercontent.com',
    iosBundleId: 'com.example.fullECommerce',
  );
}
